### ISSUE TITLE
Tetra-Cube Preset "Acolyte" Throws a Json.Exception On Import

### ISSUE THREAD

**Issue by shalsten** [morkusporkus/TableTopPowerTools#47]
Unable to import the "Acolyte" tetra-cube preset. There is also no indication of failure from the app.

System.Text.Json.JsonException: 'The JSON value could not be converted to System.Int32. Path: $.hitDice | LineNumber: 0 | BytePositionInLine: 110.'

(.monster is the usual extension, but Github does not support that)
[acolyte.txt](https://github.com/morkusporkus/DMPowerTools/files/10369320/acolyte.txt)

**Comment by benjaminsampica** [comment]
Somehow the hitdice property is coming across as a quoted string rather than a integer.

**Comment by AndrewD713** [comment]
I just exported the Acolyte from tetra-cube preset and imported it into the app just fine. Wondering if there's some user-error here. I do agree that we need error handling though.

**Comment by benjaminsampica** [comment]
On import, since we allow reviewing - I wonder if we just take what we can from the deserialization process? And swallow/ignore any deserialization exceptions?

**Comment by benjaminsampica** [comment]
> when i was trying to figure out the site i clicked "update statblock". that makes the hitdice a string

**Comment by benjaminsampica** [comment]
This is fixed by passing in different JsonSerializerOptions - specifically the options we specify now handle numbers as strings.
