### ISSUE TITLE
Create icons for Damage types

### ISSUE THREAD

**Issue by morkusporkus** [morkusporkus/TabletopPowerTools#7]

**Comment by benjaminsampica** [comment]
Here’s the icons for the different spell types.

https://svgur.com/s/Rcw


Otherwise Font Awesome Free should be able to meet the damage types with some good icon and color choice.

https://fontawesome.com/search?q=Acid&o=r&m=free&f=classic

**Comment by benjaminsampica** [comment]
https://github.com/game-icons/icons/issues/516#issuecomment-629913390

**Comment by benjaminsampica** [comment]
After doing some research, using the below strategy is probably best - creating our own component.

https://stackoverflow.com/questions/60785749/using-svgs-in-blazor-page

That uses the following icons. Looked everywhere and couldn’t find something as good.

https://game-icons.net/

**Comment by benjaminsampica** [comment]
https://seiyria.com/gameicons-font/ Try this.
